//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSchool.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARr
    {
        public string Бренд { get; set; }
        public string Модель { get; set; }
        public string Цвет { get; set; }
        public string КПП { get; set; }
        public decimal Двигатель { get; set; }
        public string Привод { get; set; }
        public string Год_выпуска { get; set; }
        public string гос__Номер { get; set; }
    }
}
