//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSchool.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecommissionedCars
    {
        public int Id { get; set; }
        public int IdCar { get; set; }
        public int IdEmployee { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
        public string ServiceLife { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
