//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSchool.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public int IdMarks { get; set; }
        public int IdStudent { get; set; }
        public int IdPlacesStudy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Marks Marks { get; set; }
        public virtual PlacesStudy PlacesStudy { get; set; }
        public virtual Student Student { get; set; }
    }
}
