//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSchool.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Group
    {
        public string ФИО { get; set; }
        public string Телефон { get; set; }
        public string Серия_и_номер { get; set; }
        public int Возраст { get; set; }
        public int Номер_группы { get; set; }
    }
}
