//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSchool.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoreticalClasses
    {
        public int Id { get; set; }
        public int IdGroup { get; set; }
        public int NumClass { get; set; }
        public int LessonNum { get; set; }
        public decimal Duration { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Groups Groups { get; set; }
    }
}
